#!/bin/bash

STRING=noCondSmallGap_000
RPSTRING=LargeCondSmallGap_000

# COUNTER=0
# MAX=50

for i in {00..251}; do
    mv $STRING$i".silo" $RPSTRING$i".silo" ;
    done

# until (( COUNTER == 10 || COUNTER == MAX )) ; do
#         rm $STRING"-s00"$COUNTER 
# 	let COUNTER=COUNTER+1
# done
# until (( COUNTER == 100 || COUNTER == MAX )) ; do
#         rm $STRING"-s0"$COUNTER 
# 	let COUNTER=COUNTER+1
# done
# until (( COUNTER == 1000 || COUNTER == MAX )) ; do
#         rm $STRING"-s"$COUNTER
# 	let COUNTER=COUNTER+1
# done


# while [ $COUNTER -lt $MAX ] ; do
#   while [ $COUNTER -lt 10 ] ; do
#        rm $STRING"-s00"$COUNTER 
#        let COUNTER=COUNTER+1
#   done
#   while [ $COUNTER -lt 100 ] ; do
#        rm $STRING"-s0"$COUNTER 
#        let COUNTER=COUNTER+1
#   done
#   while [ $COUNTER -lt 1000 ] ; do
#        rm $STRING"-s"$COUNTER
#        let COUNTER=COUNTER+1
#   done
#   # while [ $COUNTER -lt 1288 ] ; do
#   #      rm $STRING"-s"$COUNTER
#   #      let COUNTER=COUNTER+1
#   # done
# done
